# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-09T05:31:30+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class HelloWorld(BaseModel):
    message: str


class Pet(BaseModel):
    id: Optional[int] = Field(None, examples=[10])
    name: str = Field(..., examples=['doggie'])
