# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-06-09T05:31:30+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, Header, Path, Request, Depends
from sqlalchemy.orm import Session

from server.models import HelloWorld, Pet
from database.database import get_db
from database.models import Pet as PetDBModel

app = FastAPI(
    title='Sample',
    description='This is a sample OpenAPI spec.',
    license={'name': 'MIT'},
    version='0.0.1',
    servers=[{'url': 'http://127.0.0.1:8000'}],
)


@app.get('/', response_model=HelloWorld)
def get_() -> HelloWorld:
    """
    hello world
    """
    return HelloWorld(message="fastapi running")


@app.put('/pet', response_model=Pet, tags=['pet'])
def update_pet(body: Pet) -> Pet:
    """
    Update an existing pet
    """
    pass


@app.post('/pet', response_model=Pet, tags=['pet'])
def add_pet(body: Pet, db: Session = Depends(get_db)) -> Pet:
    """
    Add a new pet to the store
    https://pytutorial.com/fastapi-sqlalchemy-crud-guide/
    """
    db_item = PetDBModel(**body.model_dump())
    db.add(db_item)
    db.commit()
    db.refresh(db_item)
    return Pet(**db_item.__dict__)


@app.get('/pet/{petId}', response_model=Pet, tags=['pet'])
def get_pet_by_id(pet_id: int = Path(..., alias='petId')) -> Pet:
    """
    Find pet by ID
    """
    pass


@app.post('/pet/{petId}', response_model=None, tags=['pet'])
def update_pet_with_form(
    pet_id: int = Path(..., alias='petId'),
    name: Optional[str] = None,
    status: Optional[str] = None,
) -> None:
    """
    Updates a pet in the store with form data
    """
    pass


@app.delete('/pet/{petId}', response_model=None, tags=['pet'])
def delete_pet(
    api_key: Optional[str] = Header(None, alias='api_key'),
    pet_id: int = Path(..., alias='petId'),
) -> None:
    """
    Deletes a pet
    """
    pass
